name: ChristieVO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.92992
title: "Christie's Creative Studio"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#4e444c'
    - '#bc804a'
    - '#f4d5c0'
    - '#a93900'
  brandStrength: 0.2973581862170249
  lightness: 0.6418117629364133
  saturation: 0.6929637724533677
  rhythmicContrast: 0.6853856763336807
purpose: []
